Auto trigger sentinel failover when pod receive a SIGTERM

diff --git a/images/server/k8s-redis-ha-server b/images/server/k8s-redis-ha-server
--- a/images/server/k8s-redis-ha-server
+++ b/images/server/k8s-redis-ha-server
@@ -20,6 +20,12 @@ reset_sentinel () {
   set -e
 }
 
+sentinel_failover () {
+  set +e
+  timeout 10 redis-cli -h "$1" -p 26379 sentinel failover mymaster
+  set -e
+}
+
 redis_info_role () {
   echo "$1" | grep -e '^role:' | cut -d':' -f2 | tr -d '[:space:]'
 }
@@ -30,6 +36,30 @@ domain_ip () {
 
 server_domains () {
   /opt/bin/dig-srv "$1" | awk '{print $NF}' | sed 's/\.$//g'
+}
+
+trigger_sentinel_failover () {
+  local servers
+  servers="$(server_domains "$sentinel_domain")"
+  readonly servers
+  local s
+  >&2 echo "Trigger SENTINEL FAILOVER..."
+  for s in $servers; do
+    local s_ip
+    s_ip="$(domain_ip "$s")"
+
+    if [ -z "$s_ip" ]; then
+      >&2 echo "Failed to resolve: $s"
+      continue
+    fi
+
+    # Ignoring failed sentinels are allowed, since most of the sentinels are
+    # expected to be alive.
+    if sentinel_failover "$s_ip"; then
+      echo "SETINEL $s_ip:26379... Done"
+      break
+    fi
+  done
 }
 
 # At the end of the (succeeded) script, resetting all sentinels is necessary.
@@ -144,7 +174,36 @@ run () {
   fi
 
   reset_all_sentinels
-  exec docker-entrypoint.sh redis-server "$@"
+  docker-entrypoint.sh redis-server "$@"
 }
 
+# SIGTERM-handler
+term_handler() {
+  if redis_info "127.0.0.1" | grep "role:master"; then
+    trigger_sentinel_failover
+
+    # wait to become slave
+    while redis_info "127.0.0.1" | grep "role:master"; do
+      echo "Wait for another redis pod to become master..."
+      sleep 1
+    done
+  fi
+
+  pid=$(pidof redis-server)
+  kill -SIGTERM "$pid"
+  while kill -0 $pid 2> /dev/null; do
+    sleep 1
+  done
+}
+
+# setup handlers
+# on callback, kill the last background process, which is `tail -f /dev/null` and execute the specified handler
+trap term_handler SIGTERM
+
+# run application
 run "$@"
+
+# wait forever
+while kill -0 $(pidof redis-server) 2> /dev/null; do
+  sleep 1
+done
